In [1]:
import yfinance as yf
import pandas as pd
import os
from os.path import join
from datetime import datetime

In [2]:
path = 'financial_income_statement_data'
companys = os.listdir(path)

In [3]:
companys

['A.csv',
 'AA.csv',
 'AAC.csv',
 'AACG.csv',
 'AACI.csv',
 'AADI.csv',
 'AAIC.csv',
 'AAL.csv',
 'AAME.csv',
 'AAN.csv',
 'AAOI.csv',
 'AAON.csv',
 'AAP.csv',
 'AAPL.csv',
 'AAQC.csv',
 'AAT.csv',
 'AATC.csv',
 'AAWW.csv',
 'AB.csv',
 'ABB.csv',
 'ABBV.csv',
 'ABC.csv',
 'ABCB.csv',
 'ABCL.csv',
 'ABCM.csv',
 'ABEO.csv',
 'ABEV.csv',
 'ABG.csv',
 'ABGI.csv',
 'ABIO.csv',
 'ABM.csv',
 'ABNB.csv',
 'ABOS.csv',
 'ABR.csv',
 'ABSI.csv',
 'ABST.csv',
 'ABT.csv',
 'ABUS.csv',
 'ABVC.csv',
 'AC.csv',
 'ACA.csv',
 'ACAB.csv',
 'ACAD.csv',
 'ACAH.csv',
 'ACB.csv',
 'ACBA.csv',
 'ACCD.csv',
 'ACCO.csv',
 'ACDC.csv',
 'ACEL.csv',
 'ACER.csv',
 'ACET.csv',
 'ACGL.csv',
 'ACH.csv',
 'ACHC.csv',
 'ACHL.csv',
 'ACHR.csv',
 'ACHV.csv',
 'ACI.csv',
 'ACIU.csv',
 'ACIW.csv',
 'ACLS.csv',
 'ACLX.csv',
 'ACM.csv',
 'ACMR.csv',
 'ACN.csv',
 'ACNB.csv',
 'ACNT.csv',
 'ACON.csv',
 'ACOR.csv',
 'ACQR.csv',
 'ACR.csv',
 'ACRE.csv',
 'ACRO.csv',
 'ACRS.csv',
 'ACRV.csv',
 'ACRX.csv',
 'ACST.csv',
 'ACT.csv',
 'ACTG.csv',
 'ACVA.csv',
 'ACXP.csv',
 'ADAG.csv',
 'ADAP.csv',
 'ADBE.csv',
 'ADC.csv',
 'ADCT.csv',
 'ADD.csv',
 'ADEA.csv',
 'ADER.csv',
 'ADES.csv',
 'ADEX.csv',
 'ADI.csv',
 'ADIL.csv',
 'ADM.csv',
 'ADMA.csv',
 'ADMP.csv',
 'ADN.csv',
 'ADNT.csv',
 'ADP.csv',
 'ADPT.csv',
 'ADSE.csv',
 'ADSK.csv',
 'ADT.csv',
 'ADTH.csv',
 'ADTN.csv',
 'ADTX.csv',
 'ADUS.csv',
 'ADV.csv',
 'ADVM.csv',
 'ADX.csv',
 'ADXN.csv',
 'AEAC.csv',
 'AEE.csv',
 'AEG.csv',
 'AEHA.csv',
 'AEHL.csv',
 'AEHR.csv',
 'AEI.csv',
 'AEIS.csv',
 'AEL.csv',
 'AEM.csv',
 'AEMD.csv',
 'AENZ.csv',
 'AEO.csv',
 'AEP.csv',
 'AER.csv',
 'AERC.csv',
 'AES.csv',
 'AEVA.csv',
 'AEY.csv',
 'AEYE.csv',
 'AEZS.csv',
 'AFBI.csv',
 'AFCG.csv',
 'AFG.csv',
 'AFIB.csv',
 'AFL.csv',
 'AFMD.csv',
 'AFRI.csv',
 'AFRM.csv',
 'AFTR.csv',
 'AFYA.csv',
 'AG.csv',
 'AGAC.csv',
 'AGAE.csv',
 'AGBA.csv',
 'AGCO.csv',
 'AGEN.csv',
 'AGFS.csv',
 'AGFY.csv',
 'AGI.csv',
 'AGIL.csv',
 'AGIO.csv',
 'AGL.csv',
 'AGLE.csv',
 'AGM.csv',
 'AGMH.csv',
 'AGNC.csv',
 'AGO.csv',
 'AGR.csv',
 'AGRI.csv',
 'AGRO.csv',
 'AGRX.csv',
 'AGS.csv',
 'AGTI.csv',
 'AGX.csv',
 'AGYS.csv',
 'AGZ.csv',
 'AHCO.csv',
 'AHG.csv',
 'AHH.csv',
 'AHI.csv',
 'AHPI.csv',
 'AHT.csv',
 'AI.csv',
 'AIB.csv',
 'AIG.csv',
 'AIH.csv',
 'AIHS.csv',
 'AIMC.csv',
 'AIMD.csv',
 'AIN.csv',
 'AIP.csv',
 'AIR.csv',
 'AIRC.csv',
 'AIRG.csv',
 'AIRS.csv',
 'AIRT.csv',
 'AIT.csv',
 'AIU.csv',
 'AIV.csv',
 'AIZ.csv',
 'AJG.csv',
 'AJRD.csv',
 'AJX.csv',
 'AKA.csv',
 'AKAM.csv',
 'AKAN.csv',
 'AKBA.csv',
 'AKIC.csv',
 'AKLI.csv',
 'AKR.csv',
 'AKRO.csv',
 'AKTS.csv',
 'AKTX.csv',
 'AKU.csv',
 'AKYA.csv',
 'AL.csv',
 'ALB.csv',
 'ALBO.csv',
 'ALBT.csv',
 'ALC.csv',
 'ALCC.csv',
 'ALCO.csv',
 'ALDX.csv',
 'ALE.csv',
 'ALEC.csv',
 'ALEX.csv',
 'ALG.csv',
 'ALGM.csv',
 'ALGN.csv',
 'ALGS.csv',
 'ALGT.csv',
 'ALHC.csv',
 'ALIM.csv',
 'ALIT.csv',
 'ALK.csv',
 'ALKS.csv',
 'ALKT.csv',
 'ALL.csv',
 'ALLE.csv',
 'ALLG.csv',
 'ALLK.csv',
 'ALLO.csv',
 'ALLR.csv',
 'ALLT.csv',
 'ALLY.csv',
 'ALNY.csv',
 'ALOT.csv',
 'ALPA.csv',
 'ALPN.csv',
 'ALPP.csv',
 'ALPS.csv',
 'ALR.csv',
 'ALRM.csv',
 'ALRN.csv',
 'ALRS.csv',
 'ALSN.csv',
 'ALT.csv',
 'ALTG.csv',
 'ALTO.csv',
 'ALTR.csv',
 'ALTU.csv',
 'ALV.csv',
 'ALVO.csv',
 'ALVR.csv',
 'ALX.csv',
 'ALXO.csv',
 'ALYA.csv',
 'ALZN.csv',
 'AM.csv',
 'AMAL.csv',
 'AMAM.csv',
 'AMAO.csv',
 'AMAT.csv',
 'AMBA.csv',
 'AMBC.csv',
 'AMBP.csv',
 'AMC.csv',
 'AMCI.csv',
 'AMCR.csv',
 'AMCX.csv',
 'AMD.csv',
 'AME.csv',
 'AMED.csv',
 'AMEH.csv',
 'AMG.csv',
 'AMGN.csv',
 'AMH.csv',
 'AMK.csv',
 'AMKR.csv',
 'AMLX.csv',
 'AMN.csv',
 'AMNB.csv',
 'AMOT.csv',
 'AMP.csv',
 'AMPG.csv',
 'AMPH.csv',
 'AMPL.csv',
 'AMPS.csv',
 'AMPX.csv',
 'AMPY.csv',
 'AMR.csv',
 'AMRC.csv',
 'AMRK.csv',
 'AMRN.csv',
 'AMRS.csv',
 'AMRX.csv',
 'AMSC.csv',
 'AMSF.csv',
 'AMST.csv',
 'AMSWA.csv',
 'AMT.csv',
 'AMTB.csv',
 'AMTD.csv',
 'AMTI.csv',
 'AMTX.csv',
 'AMV.csv',
 'AMWD.csv',
 'AMWL.csv',
 'AMX.csv',
 'AMYT.csv',
 'AMZN.csv',
 'AN.csv',
 'ANAB.csv',
 'ANAC.csv',
 'ANDE.csv',
 'ANEB.csv',
 'ANET.csv',
 'ANF.csv',
 'ANGH.csv',
 'ANGI.csv',
 'ANGN.csv',
 'ANGO.csv',
 'ANIK.csv',
 'ANIP.csv',
 'ANIX.csv',
 'ANNX.csv',
 'ANPC.csv',
 'ANSS.csv',
 'ANTE.csv',
 'ANTX.csv',
 'ANVS.csv',
 'ANY.csv',
 'ANZU.csv',
 'AOMR.csv',
 'AON.csv',
 'AORT.csv',
 'AOS.csv',
 'AOSL.csv',
 'AOUT.csv',
 'AP.csv',
 'APA.csv',
 'APAC.csv',
 'APAM.csv',
 'APD.csv',
 'APDN.csv',
 'APEI.csv',
 'APEN.csv',
 'APG.csv',
 'APGB.csv',
 'APGN.csv',
 'APH.csv',
 'API.csv',
 'APLD.csv',
 'APLE.csv',
 'APLS.csv',
 'APLT.csv',
 'APM.csv',
 'APMI.csv',
 'APN.csv',
 'APO.csv',
 'APOG.csv',
 'APP.csv',
 'APPF.csv',
 'APPH.csv',
 'APPN.csv',
 'APPS.csv',
 'APRE.csv',
 'APRN.csv',
 'APTM.csv',
 'APTO.csv',
 'APTV.csv',
 'APTX.csv',
 'APVO.csv',
 'APWC.csv',
 'APYX.csv',
 'AQB.csv',
 'AQMS.csv',
 'AQN.csv',
 'AQST.csv',
 'AQU.csv',
 'AQUA.csv',
 'AR.csv',
 'ARAV.csv',
 'ARAY.csv',
 'ARBE.csv',
 'ARBG.csv',
 'ARBK.csv',
 'ARC.csv',
 'ARCB.csv',
 'ARCC.csv',
 'ARCE.csv',
 'ARCH.csv',
 'ARCK.csv',
 'ARCO.csv',
 'ARCT.csv',
 'ARDS.csv',
 'ARDX.csv',
 'ARE.csv',
 'AREB.csv',
 'AREC.csv',
 'ARES.csv',
 'ARGO.csv',
 'ARGX.csv',
 'ARHS.csv',
 'ARI.csv',
 'ARIS.csv',
 'ARIZ.csv',
 'ARKO.csv',
 'ARKR.csv',
 'ARL.csv',
 'ARLO.csv',
 'ARLP.csv',
 'ARMK.csv',
 'ARNC.csv',
 'AROC.csv',
 'AROW.csv',
 'ARQQ.csv',
 'ARQT.csv',
 'ARR.csv',
 'ARRW.csv',
 'ARRY.csv',
 'ARTE.csv',
 'ARTL.csv',
 'ARTNA.csv',
 'ARTW.csv',
 'ARVL.csv',
 'ARVN.csv',
 'ARW.csv',
 'ARWR.csv',
 'ARYD.csv',
 'ARYE.csv',
 'ASAI.csv',
 'ASAN.csv',
 'ASAP.csv',
 'ASAX.csv',
 'ASB.csv',
 'ASC.csv',
 'ASCA.csv',
 'ASGN.csv',
 'ASH.csv',
 'ASIX.csv',
 'ASLE.csv',
 'ASLN.csv',
 'ASMB.csv',
 'ASML.csv',
 'ASND.csv',
 'ASNS.csv',
 'ASO.csv',
 'ASPA.csv',
 'ASPI.csv',
 'ASPN.csv',
 'ASPS.csv',
 'ASPU.csv',
 'ASR.csv',
 'ASRT.csv',
 'ASRV.csv',
 'ASTC.csv',
 'ASTE.csv',
 'ASTI.csv',
 'ASTL.csv',
 'ASTR.csv',
 'ASTS.csv',
 'ASUR.csv',
 'ASX.csv',
 'ASYS.csv',
 'ATAI.csv',
 'ATAK.csv',
 'ATAQ.csv',
 'ATAT.csv',
 'ATCO.csv',
 'ATCX.csv',
 'ATEC.csv',
 'ATEN.csv',
 'ATER.csv',
 'ATEX.csv',
 'ATGE.csv',
 'ATHA.csv',
 'ATHE.csv',
 'ATHM.csv',
 'ATHX.csv',
 'ATI.csv',
 'ATIF.csv',
 'ATIP.csv',
 'ATKR.csv',
 'ATLC.csv',
 'ATLO.csv',
 'ATNF.csv',
 'ATNI.csv',
 'ATNX.csv',
 'ATO.csv',
 'ATOM.csv',
 'ATOS.csv',
 'ATR.csv',
 'ATRA.csv',
 'ATRC.csv',
 'ATRI.csv',
 'ATRO.csv',
 'ATSG.csv',
 'ATTO.csv',
 'ATUS.csv',
 'ATVI.csv',
 'ATXG.csv',
 'ATXI.csv',
 'ATXS.csv',
 'ATY.csv',
 'AU.csv',
 'AUB.csv',
 'AUBN.csv',
 'AUD.csv',
 'AUDC.csv',
 'AUGX.csv',
 'AUID.csv',
 'AUPH.csv',
 'AUR.csv',
 'AURA.csv',
 'AURC.csv',
 'AUTL.csv',
 'AUUD.csv',
 'AUVI.csv',
 'AUY.csv',
 'AVA.csv',
 'AVAH.csv',
 'AVAL.csv',
 'AVAN.csv',
 'AVAV.csv',
 'AVB.csv',
 'AVCT.csv',
 'AVD.csv',
 'AVDL.csv',
 'AVDX.csv',
 'AVEO.csv',
 'AVGO.csv',
 'AVGR.csv',
 'AVHI.csv',
 'AVID.csv',
 'AVIR.csv',
 'AVNS.csv',
 'AVNT.csv',
 'AVNW.csv',
 'AVO.csv',
 'AVPT.csv',
 'AVRO.csv',
 'AVT.csv',
 'AVTE.csv',
 'AVTR.csv',
 'AVTX.csv',
 'AVXL.csv',
 'AVY.csv',
 'AVYA.csv',
 'AWH.csv',
 'AWI.csv',
 'AWK.csv',
 'AWR.csv',
 'AWRE.csv',
 'AX.csv',
 'AXAC.csv',
 'AXDX.csv',
 'AXGN.csv',
 'AXL.csv',
 'AXLA.csv',
 'AXNX.csv',
 'AXON.csv',
 'AXP.csv',
 'AXR.csv',
 'AXS.csv',
 'AXSM.csv',
 'AXTA.csv',
 'AXTI.csv',
 'AY.csv',
 'AYI.csv',
 'AYLA.csv',
 'AYRO.csv',
 'AYTU.csv',
 'AYX.csv',
 'AZ.csv',
 'AZEK.csv',
 'AZN.csv',
 'AZO.csv',
 'AZPN.csv',
 'AZRE.csv',
 'AZTA.csv',
 'AZUL.csv',
 'AZYO.csv',
 'AZZ.csv',
 'B.csv',
 'BA.csv',
 'BABA.csv',
 'BAC.csv',
 'BACA.csv',
 'BACK.csv',
 'BAFN.csv',
 'BAH.csv',
 'BAK.csv',
 'BALL.csv',
 'BALY.csv',
 'BANC.csv',
 'BAND.csv',
 'BANF.csv',
 'BANR.csv',
 'BANX.csv',
 'BAOS.csv',
 'BAP.csv',
 'BARK.csv',
 'BASE.csv',
 'BATRA.csv',
 'BATRK.csv',
 'BAX.csv',
 'BB.csv',
 'BBAI.csv',
 'BBAR.csv',
 'BBBY.csv',
 'BBCP.csv',
 'BBD.csv',
 'BBDC.csv',
 'BBDO.csv',
 'BBGI.csv',
 'BBIG.csv',
 'BBIO.csv',
 'BBLG.csv',
 'BBLN.csv',
 'BBSI.csv',
 'BBU.csv',
 'BBVA.csv',
 'BBW.csv',
 'BBWI.csv',
 'BBY.csv',
 'BC.csv',
 'BCAB.csv',
 'BCBP.csv',
 'BCC.csv',
 'BCDA.csv',
 'BCE.csv',
 'BCEL.csv',
 'BCH.csv',
 'BCLI.csv',
 'BCML.csv',
 'BCO.csv',
 'BCOR.csv',
 'BCOV.csv',
 'BCOW.csv',
 'BCPC.csv',
 'BCRX.csv',
 'BCS.csv',
 'BCSF.csv',
 'BCTX.csv',
 'BCYC.csv',
 'BDC.csv',
 'BDN.csv',
 'BDSX.csv',
 'BDTX.csv',
 'BDX.csv',
 'BE.csv',
 'BEAM.csv',
 'BEAT.csv',
 'BECN.csv',
 'BEDU.csv',
 'BEEM.csv',
 'BEKE.csv',
 'BELFA.csv',
 'BELFB.csv',
 'BEN.csv',
 'BEP.csv',
 'BEPC.csv',
 'BERY.csv',
 'BEST.csv',
 'BFAM.csv',
 'BFC.csv',
 'BFH.csv',
 'BFI.csv',
 'BFIN.csv',
 'BFLY.csv',
 'BFRI.csv',
 'BFS.csv',
 'BFST.csv',
 'BG.csv',
 'BGCP.csv',
 'BGFV.csv',
 'BGNE.csv',
 'BGRY.csv',
 'BGS.csv',
 'BGSF.csv',
 'BGSX.csv',
 'BGXX.csv',
 'BH.csv',
 'BHAT.csv',
 'BHC.csv',
 'BHE.csv',
 'BHF.csv',
 'BHG.csv',
 'BHIL.csv',
 'BHLB.csv',
 'BHP.csv',
 'BHR.csv',
 'BHVN.csv',
 'BIAF.csv',
 'BIDU.csv',
 'BIG.csv',
 'BIGC.csv',
 'BIIB.csv',
 'BILI.csv',
 'BILL.csv',
 'BIMI.csv',
 'BIO.csv',
 'BIOC.csv',
 'BIOL.csv',
 'BIOR.csv',
 'BIOT.csv',
 'BIOX.csv',
 'BIP.csv',
 'BIRD.csv',
 'BITE.csv',
 'BITF.csv',
 'BIVI.csv',
 'BJ.csv',
 'BJDX.csv',
 'BJRI.csv',
 'BK.csv',
 'BKCC.csv',
 'BKD.csv',
 'BKE.csv',
 'BKH.csv',
 'BKI.csv',
 'BKKT.csv',
 'BKNG.csv',
 'BKR.csv',
 'BKSC.csv',
 'BKSY.csv',
 'BKU.csv',
 'BKYI.csv',
 'BL.csv',
 'BLBD.csv',
 'BLBX.csv',
 'BLCM.csv',
 'BLD.csv',
 'BLDE.csv',
 'BLDP.csv',
 'BLDR.csv',
 'BLEU.csv',
 'BLFS.csv',
 'BLFY.csv',
 'BLI.csv',
 'BLIN.csv',
 'BLK.csv',
 'BLKB.csv',
 'BLMN.csv',
 'BLND.csv',
 'BLNG.csv',
 'BLNK.csv',
 'BLPH.csv',
 'BLRX.csv',
 'BLTE.csv',
 'BLU.csv',
 'BLUA.csv',
 'BLUE.csv',
 'BLX.csv',
 'BLZE.csv',
 'BMA.csv',
 'BMAC.csv',
 'BMBL.csv',
 'BMEA.csv',
 'BMI.csv',
 'BMO.csv',
 'BMRA.csv',
 'BMRC.csv',
 'BMRN.csv',
 'BMY.csv',
 'BN.csv',
 'BNED.csv',
 'BNFT.csv',
 'BNGO.csv',
 'BNIX.csv',
 'BNL.csv',
 'BNNR.csv',
 'BNOX.csv',
 'BNR.csv',
 'BNRE.csv',
 'BNRG.csv',
 'BNS.csv',
 'BNSO.csv',
 'BNTC.csv',
 'BNTX.csv',
 'BNXTF.csv',
 'BOAC.csv',
 'BOC.csv',
 'BODY.csv',
 'BOH.csv',
 'BOKF.csv',
 'BOLT.csv',
 'BON.csv',
 'BOOM.csv',
 'BOOT.csv',
 'BORR.csv',
 'BOSC.csv',
 'BOTJ.csv',
 'BOWL.csv',
 'BOX.csv',
 'BOXD.csv',
 'BOXL.csv',
 'BP.csv',
 'BPAC.csv',
 'BPMC.csv',
 'BPOP.csv',
 'BPRN.csv',
 'BPT.csv',
 'BPTH.csv',
 'BPTS.csv',
 'BQ.csv',
 'BR.csv',
 'BRAG.csv',
 'BRBR.csv',
 'BRC.csv',
 'BRCC.csv',
 'BRD.csv',
 'BRDG.csv',
 'BRDS.csv',
 'BREZ.csv',
 'BRFH.csv',
 'BRFS.csv',
 'BRID.csv',
 'BRIV.csv',
 'BRKL.csv',
 'BRKR.csv',
 'BRLI.csv',
 'BRLT.csv',
 'BRMK.csv',
 'BRO.csv',
 'BROG.csv',
 'BROS.csv',
 'BRP.csv',
 'BRQS.csv',
 'BRSP.csv',
 'BRT.csv',
 'BRTX.csv',
 'BRX.csv',
 'BRY.csv',
 'BRZE.csv',
 'BSAC.csv',
 'BSAQ.csv',
 'BSBK.csv',
 'BSBR.csv',
 'BSET.csv',
 'BSFC.csv',
 'BSGA.csv',
 'BSGM.csv',
 'BSIG.csv',
 'BSM.csv',
 'BSMX.csv',
 'BSQR.csv',
 'BSRR.csv',
 'BSVN.csv',
 'BSX.csv',
 'BSY.csv',
 'BTAI.csv',
 'BTBD.csv',
 'BTBT.csv',
 'BTCM.csv',
 'BTCS.csv',
 'BTCY.csv',
 'BTI.csv',
 'BTMD.csv',
 'BTOG.csv',
 'BTTX.csv',
 'BTU.csv',
 'BTWN.csv',
 'BUD.csv',
 'BUR.csv',
 'BURL.csv',
 'BUSE.csv',
 'BV.csv',
 'BVH.csv',
 'BVN.csv',
 'BVS.csv',
 'BVXV.csv',
 'BW.csv',
 'BWA.csv',
 'BWAC.csv',
 'BWAY.csv',
 'BWB.csv',
 'BWC.csv',
 'BWEN.csv',
 'BWFG.csv',
 'BWMN.csv',
 'BWMX.csv',
 'BWV.csv',
 'BWXT.csv',
 'BX.csv',
 'BXC.csv',
 'BXMT.csv',
 'BXP.csv',
 'BXRX.csv',
 'BXSL.csv',
 'BY.csv',
 'BYD.csv',
 'BYFC.csv',
 'BYN.csv',
 'BYND.csv',
 'BYRN.csv',
 'BYSI.csv',
 'BYTS.csv',
 'BZ.csv',
 'BZFD.csv',
 'BZH.csv',
 'BZUN.csv',
 'C.csv',
 'CAAP.csv',
 'CAAS.csv',
 'CABA.csv',
 'CABO.csv',
 'CAC.csv',
 'CACC.csv',
 'CACI.csv',
 'CACO.csv',
 'CADE.csv',
 'CADL.csv',
 'CAE.csv',
 'CAG.csv',
 'CAH.csv',
 'CAJ.csv',
 'CAKE.csv',
 'CAL.csv',
 'CALA.csv',
 'CALB.csv',
 'CALM.csv',
 'CALT.csv',
 'CALX.csv',
 'CAMP.csv',
 'CAMT.csv',
 'CAN.csv',
 'CANG.csv',
 'CANO.csv',
 'CAPL.csv',
 'CAPR.csv',
 'CAR.csv',
 'CARA.csv',
 'CARE.csv',
 'CARG.csv',
 'CARR.csv',
 'CARS.csv',
 'CARV.csv',
 'CASA.csv',
 'CASH.csv',
 'CASI.csv',
 'CASS.csv',
 'CASY.csv',
 'CAT.csv',
 'CATC.csv',
 'CATO.csv',
 'CATY.csv',
 'CB.csv',
 'CBAN.csv',
 'CBAT.csv',
 'CBAY.csv',
 'CBD.csv',
 'CBFV.csv',
 'CBIO.csv',
 'CBL.csv',
 'CBNK.csv',
 'CBRE.csv',
 'CBRG.csv',
 'CBRL.csv',
 'CBSH.csv',
 'CBT.csv',
 'CBU.csv',
 'CBZ.csv',
 'CC.csv',
 'CCAI.csv',
 'CCAP.csv',
 'CCB.csv',
 'CCBG.csv',
 'CCCC.csv',
 'CCCS.csv',
 'CCEP.csv',
 'CCI.csv',
 'CCJ.csv',
 'CCK.csv',
 'CCL.csv',
 'CCLP.csv',
 'CCM.csv',
 'CCNC.csv',
 'CCNE.csv',
 'CCO.csv',
 'CCOI.csv',
 'CCRD.csv',
 'CCRN.csv',
 'CCS.csv',
 'CCSI.csv',
 'CCU.csv',
 'CCV.csv',
 'CCVI.csv',
 'CD.csv',
 'CDAK.csv',
 'CDAY.csv',
 'CDE.csv',
 'CDIO.csv',
 'CDLX.csv',
 'CDMO.csv',
 'CDNA.csv',
 ...]

In [4]:
ticker_file = pd.read_csv(join(path, companys[13]))

In [5]:
ticker_file

,Unnamed: 0,Revenue,Cost Of Goods Sold,Gross Profit,Research And Development Expenses,SG&A Expenses,Other Operating Income Or Expenses,Operating Expenses,Operating Income,Total Non-Operating Income/Expense,...,EBIT,Basic Shares Outstanding,Shares Outstanding,Basic EPS,EPS - Earnings Per Share,ticker,industry,sector,company_full_name,country
0,2022-09-30,394328.0,223546.0,170782.0,26251.0,25094.0,NaN,51345.0,119437.0,-334.0,...,119437.0,16215.96,16325.82,6.1500,6.1100,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
1,2021-09-30,365817.0,212981.0,152836.0,21914.0,21973.0,NaN,43887.0,108949.0,258.0,...,108949.0,16701.27,16864.92,5.6700,5.6100,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
2,2020-09-30,274515.0,169559.0,104956.0,18752.0,19916.0,NaN,38668.0,66288.0,803.0,...,66288.0,17352.12,17528.21,3.3100,3.2800,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
3,2019-09-30,260174.0,161782.0,98392.0,16217.0,18245.0,NaN,34462.0,63930.0,1807.0,...,63930.0,18471.34,18595.65,2.9900,2.9700,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
4,2018-09-30,265595.0,163756.0,101839.0,14236.0,16705.0,NaN,30941.0,70898.0,2005.0,...,70898.0,19821.51,20000.44,3.0000,2.9800,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
5,2017-09-30,229234.0,141048.0,88186.0,11581.0,15261.0,NaN,26842.0,61344.0,2745.0,...,61344.0,20868.97,21006.77,2.3175,2.3025,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
6,2016-09-30,215639.0,131376.0,84263.0,10045.0,14194.0,NaN,24239.0,60024.0,1348.0,...,60024.0,21883.28,22001.12,2.0875,2.0775,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
7,2015-09-30,233715.0,140089.0,93626.0,8067.0,14329.0,NaN,22396.0,71230.0,1285.0,...,71230.0,23013.68,23172.28,2.3200,2.3050,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
8,2014-09-30,182795.0,112258.0,70537.0,6041.0,11993.0,NaN,18034.0,52503.0,980.0,...,52503.0,24342.29,24490.65,1.6225,1.6125,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
9,2013-09-30,170910.0,106606.0,64304.0,4475.0,10830.0,NaN,15305.0,48999.0,1156.0,...,48999.0,25909.28,26086.54,1.4300,1.4200,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
10,2012-09-30,156508.0,87846.0,68662.0,3381.0,10040.0,NaN,13421.0,55241.0,522.0,...,55241.0,26174.90,26469.93,1.5950,1.5775,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
11,2011-09-30,108249.0,64431.0,43818.0,2429.0,7599.0,NaN,10028.0,33790.0,415.0,...,33790.0,25879.22,26226.06,1.0018,0.9886,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
12,2010-09-30,65225.0,39541.0,25684.0,1782.0,5517.0,NaN,7299.0,18385.0,155.0,...,18385.0,25464.91,25891.94,0.5504,0.5411,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States
13,2009-09-30,42905.0,25683.0,17222.0,1333.0,4149.0,NaN,5482.0,11740.0,326.0,...,11740.0,25004.45,25396.14,0.3293,0.3243,AAPL,Computers - Minicomputers,Computer and Technology,Apple,United States

In [6]:
ticker = companys[13][:-4]

In [7]:
ticker

'AAPL'

In [8]:
stock_info = yf.Ticker(ticker)

In [9]:
hist = stock_info.history(period="max", interval = "1mo")

In [10]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1985-01-01,0.101176,0.108125,0.096834,0.100742,6.366416e+09,0.00,0.0
1985-02-01,0.100742,0.106822,0.085978,0.085978,4.733389e+09,0.00,0.0
1985-03-01,0.085978,0.090320,0.072083,0.076859,4.615587e+09,0.00,0.0
1985-04-01,0.076859,0.079900,0.068175,0.073820,2.868029e+09,0.00,0.0
1985-05-01,0.073820,0.077293,0.058622,0.060359,4.639130e+09,0.00,0.0
...,...,...,...,...,...,...,...
2022-10-01,137.981112,157.239158,134.147460,153.086044,1.868140e+09,0.00,0.0
2022-11-01,154.823179,155.192561,134.157462,147.784851,1.724691e+09,0.00,0.0
2022-11-04,NaN,NaN,NaN,NaN,NaN,0.23,0.0
2022-12-01,148.210007,150.919998,125.870003,129.610001,1.598444e+09,0.00,0.0
2022-12-29,127.989998,130.479996,127.815002,129.610001,7.554162e+07,0.00,0.0

In [11]:
hist = hist.reset_index()

In [12]:
hist['Date'] = pd.to_datetime(hist['Date'])
hist['year'] = hist['Date'].dt.year

In [13]:
hist

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,year
0,1985-01-01,0.101176,0.108125,0.096834,0.100742,6.366416e+09,0.00,0.0,1985
1,1985-02-01,0.100742,0.106822,0.085978,0.085978,4.733389e+09,0.00,0.0,1985
2,1985-03-01,0.085978,0.090320,0.072083,0.076859,4.615587e+09,0.00,0.0,1985
3,1985-04-01,0.076859,0.079900,0.068175,0.073820,2.868029e+09,0.00,0.0,1985
4,1985-05-01,0.073820,0.077293,0.058622,0.060359,4.639130e+09,0.00,0.0,1985
...,...,...,...,...,...,...,...,...,...
533,2022-10-01,137.981112,157.239158,134.147460,153.086044,1.868140e+09,0.00,0.0,2022
534,2022-11-01,154.823179,155.192561,134.157462,147.784851,1.724691e+09,0.00,0.0,2022
535,2022-11-04,NaN,NaN,NaN,NaN,NaN,0.23,0.0,2022
536,2022-12-01,148.210007,150.919998,125.870003,129.610001,1.598444e+09,0.00,0.0,2022
537,2022-12-29,127.989998,130.479996,127.815002,129.610001,7.554162e+07,0.00,0.0,2022

In [14]:
histgrouped = hist.groupby(['year']).agg({'Close':'last'})

In [15]:
histgrouped

           Close
year
1985    0.076425
1986    0.140692
1987    0.293266
1988    0.283436
1989    0.250664
1990    0.309572
1991    0.409661
1992    0.437975
1993    0.217048
1994    0.293474
1995    0.242596
1996    0.158877
1997    0.099893
1998    0.311570
1999    0.782493
2000    0.226424
2001    0.333356
2002    0.218128
2003    0.325289
2004    0.980280
2005    2.188582
2006    2.582826
2007    6.030247
2008    2.598352
2009    6.415356
2010    9.819857
2011   12.329616
2012   16.344992
2013   17.663952
2014   24.839497
2015   24.090899
2016   27.097544
2017   40.230190
2018   38.061707
2019   71.920570
2020  131.116028
2021  176.545380
2022  129.610001

In [16]:
histgrouped = histgrouped.reset_index()

In [17]:
histgrouped['ticker'] = ticker

In [19]:
histgrouped['Growth -1'] = (histgrouped['Close'] - histgrouped['Close'].shift(periods=1)) /  histgrouped['Close'].shift(periods=1)
histgrouped['Growth +1'] = (histgrouped['Close'].shift(periods=-1) - histgrouped['Close']) /  histgrouped['Close']

In [20]:
histgrouped['avgGrowth -10'] = histgrouped['Growth -1'].rolling(min_periods=10, window=10).sum() / 10
histgrouped['avgGrowth -5'] = histgrouped['Growth -1'].rolling(min_periods=5, window=5).sum() / 5

In [21]:
histgrouped

    year       Close ticker  Growth -1  Growth +1  avgGrowth -10  avgGrowth -5
0   1985    0.076425   AAPL        NaN   0.840920            NaN           NaN
1   1986    0.140692   AAPL   0.840920   1.084446            NaN           NaN
2   1987    0.293266   AAPL   1.084446  -0.033519            NaN           NaN
3   1988    0.283436   AAPL  -0.033519  -0.115623            NaN           NaN
4   1989    0.250664   AAPL  -0.115623   0.235009            NaN           NaN
5   1990    0.309572   AAPL   0.235009   0.323313            NaN      0.402247
6   1991    0.409661   AAPL   0.323313   0.069115            NaN      0.298725
7   1992    0.437975   AAPL   0.069115  -0.504428            NaN      0.095659
8   1993    0.217048   AAPL  -0.504428   0.352114            NaN      0.001477
9   1994    0.293474   AAPL   0.352114  -0.173362            NaN      0.095024
10  1995    0.242596   AAPL  -0.173362  -0.345097       0.207798      0.013350
11  1996    0.158877   AAPL  -0.345097  -0.371255       0.089197     -0.120332
12  1997    0.099893   AAPL  -0.371255   2.119031      -0.056373     -0.208406
13  1998    0.311570   AAPL   2.119031   1.511454       0.158882      0.316286
14  1999    0.782493   AAPL   1.511454  -0.710638       0.321589      0.548154
15  2000    0.226424   AAPL  -0.710638   0.472267       0.227025      0.440699
16  2001    0.333356   AAPL   0.472267  -0.345661       0.241920      0.604172
17  2002    0.218128   AAPL  -0.345661   0.491276       0.200442      0.609291
18  2003    0.325289   AAPL   0.491276   2.013570       0.300013      0.283739
19  2004    0.980280   AAPL   2.013570   1.232609       0.466158      0.384163
20  2005    2.188582   AAPL   1.232609   0.180137       0.606756      0.772812
21  2006    2.582826   AAPL   0.180137   1.334748       0.659279      0.714386
22  2007    6.030247   AAPL   1.334748  -0.569114       0.829879      1.050468
23  2008    2.598352   AAPL  -0.569114   1.469010       0.561065      0.838390
24  2009    6.415356   AAPL   1.469010   0.530680       0.556820      0.729478
25  2010    9.819857   AAPL   0.530680   0.255580       0.680952      0.589092
26  2011   12.329616   AAPL   0.255580   0.325669       0.659283      0.604181
27  2012   16.344992   AAPL   0.325669   0.080695       0.726416      0.402365
28  2013   17.663952   AAPL   0.080695   0.406225       0.685358      0.532327
29  2014   24.839497   AAPL   0.406225  -0.030137       0.524624      0.319770
30  2015   24.090899   AAPL  -0.030137   0.124804       0.398349      0.207606
31  2016   27.097544   AAPL   0.124804   0.484643       0.392816      0.181451
32  2017   40.230190   AAPL   0.484643  -0.053902       0.307806      0.213246
33  2018   38.061707   AAPL  -0.053902   0.889578       0.359327      0.186327
34  2019   71.920570   AAPL   0.889578   0.823067       0.301384      0.282997
35  2020  131.116028   AAPL   0.823067   0.346482       0.330622      0.453638
36  2021  176.545380   AAPL   0.346482  -0.265854       0.339713      0.497974
37  2022  129.610001   AAPL  -0.265854        NaN       0.280560      0.347874

In [22]:
filter_years = pd.to_datetime(ticker_file['Unnamed: 0']).dt.year.tolist()

In [23]:
histgrouped_filtered = histgrouped[histgrouped['year'].isin(filter_years)]

In [24]:
histgrouped_filtered.reset_index(names=['longevity'], inplace=True)

In [25]:
histgrouped_filtered

,longevity,year,Close,ticker,Growth -1,Growth +1,avgGrowth -10,avgGrowth -5
0,24,2009,6.415356,AAPL,1.469010,0.530680,0.556820,0.729478
1,25,2010,9.819857,AAPL,0.530680,0.255580,0.680952,0.589092
2,26,2011,12.329616,AAPL,0.255580,0.325669,0.659283,0.604181
3,27,2012,16.344992,AAPL,0.325669,0.080695,0.726416,0.402365
4,28,2013,17.663952,AAPL,0.080695,0.406225,0.685358,0.532327
5,29,2014,24.839497,AAPL,0.406225,-0.030137,0.524624,0.319770
6,30,2015,24.090899,AAPL,-0.030137,0.124804,0.398349,0.207606
7,31,2016,27.097544,AAPL,0.124804,0.484643,0.392816,0.181451
8,32,2017,40.230190,AAPL,0.484643,-0.053902,0.307806,0.213246
9,33,2018,38.061707,AAPL,-0.053902,0.889578,0.359327,0.186327
10,34,2019,71.920570,AAPL,0.889578,0.823067,0.301384,0.282997
11,35,2020,131.116028,AAPL,0.823067,0.346482,0.330622,0.453638
12,36,2021,176.545380,AAPL,0.346482,-0.265854,0.339713,0.497974
13,37,2022,129.610001,AAPL,-0.265854,NaN,0.280560,0.347874